package com.island.ohara.rest
import java.util.Objects

import com.island.ohara.rest.ConnectorJson.ConnectorResponse

import scala.collection.mutable

/**
  * a base class used to collect the config of source/sink connector when creating
  */
abstract class ConnectorCreator {
  protected var name: String = _
  protected var clzName: String = _
  protected var topicNames: Seq[String] = _
  protected var taskMax: Int = -1
  protected var config: mutable.HashMap[String, String] = _
  protected var _disableKeyConverter: Boolean = false
  protected var _disableValueConverter: Boolean = false

  /**
    * config the key converter be org.apache.kafka.connect.converters.ByteArrayConverter. It is useful if the data in topic
    * your connector want to take is byte array and is generated by kafka producer. For example, the source is RowProducer,
    * and the target is RowSinkConnector.
    *
    * @return this one
    */
  def disableKeyConverter(): this.type = {
    this._disableKeyConverter = true
    this
  }

  /**
    * config the value converter be org.apache.kafka.connect.converters.ByteArrayConverter. It is useful if the data in topic
    * your connector want to take is byte array and is generated by kafka producer. For example, the source is RowProducer,
    * and the target is RowSinkConnector.
    *
    * @return this one
    */
  def disableValueConverter(): this.type = {
    this._disableValueConverter = true
    this
  }

  /**
    * config the converter be org.apache.kafka.connect.converters.ByteArrayConverter. It is useful if the data in topic
    * your connector want to take is byte array and is generated by kafka producer. For example, the source is RowProducer,
    * and the target is RowSinkConnector.
    *
    * @return this one
    */
  def disableConverter(): this.type = {
    this._disableKeyConverter = true
    this._disableValueConverter = true
    this
  }

  /**
    * set the connector name. It should be a unique name.
    *
    * @param name connector name
    * @return this one
    */
  def name(name: String): this.type = {
    this.name = name
    this
  }

  /**
    * set the connector class. The class must be loaded in class loader otherwise it will fail to create the connector.
    *
    * @param clz connector class
    * @return this one
    */
  def connectorClass(clzName: String): this.type = {
    this.clzName = clzName
    this
  }

  /**
    * set the connector class. The class must be loaded in class loader otherwise it will fail to create the connector.
    *
    * @param clz connector class
    * @return this one
    */
  def connectorClass[T](clz: Class[T]): this.type = {
    this.clzName = clz.getName
    this
  }

  /**
    * set the topic in which you have interest.
    *
    * @param topicName topic
    * @return this one
    */
  def topic(topicName: String): this.type = {
    this.topicNames = Seq(topicName)
    this
  }

  /**
    * the max number of sink task you want to create
    *
    * @param taskMax max number of sink task
    * @return this one
    */
  def taskNumber(taskMax: Int): this.type = {
    this.taskMax = taskMax
    this
  }

  def config(key: String, value: String): this.type = {
    if (config == null) config = new mutable.HashMap[String, String]()
    config += (key -> value)
    this
  }

  /**
    * extra config passed to sink connector. This config is optional.
    *
    * @param config config
    * @return this one
    */
  def config(config: Map[String, String]): this.type = {
    this.config = new mutable.HashMap[String, String]()
    this.config ++= config
    this
  }

  /**
    * send the request to create the sink connector.
    *
    * @return this one
    */
  def run(): ConnectorResponse

  protected def checkArgument(): Unit = {
    Objects.requireNonNull(name)
    Objects.requireNonNull(clzName)
    Objects.requireNonNull(topicNames)
    if (topicNames.isEmpty) throw new IllegalArgumentException(s"You must specify 1+ topic names")
    if (taskMax <= 0) throw new IllegalArgumentException(s"taskMax should be bigger than zero, current:$taskMax")
  }
}
